[package]
name = "vk-remove-comments"
version = "0.1.0"
authors = ["Nikolay Chechulin <nchechulin@aol.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.8.0"
regex = "1.5.4"
encoding_rs = "0.8.28"
encoding_rs_io = "0.1.7"
reqwest = "0.11.3"
tokio = { version = "1.8.4", features = ["full"] }
pbr = "1.0.4"
